Repository ArmaForces/FriendlyTracker, pull requests merged in 2020-01, with the labels that each got.

#6 Fix GPS detection not working
  addons/friendly_tracker/functions/fnc_hasTracker.sqf
Labels: bugfix

#7 Fix markers being created for all players and groups
  addons/friendly_tracker/functions/fnc_loop.sqf
Labels: bugfix

#8 Add automatic release workflows
  .github/labels.json
  .github/release-drafter.yml
  .github/workflows/labels.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
Labels: enhancement, ignore changelog

#9 Bump version for release 1.0.1
  addons/main/script_mod.hpp
  addons/main/script_version.hpp
Labels: enhancement, ignore changelog

#10 Fix release drafter condition
  .github/workflows/release-drafter.yml
Labels: bugfix, ignore changelog

#12 Move addon description to main README
  README.md
  addons/friendly_tracker/README.md
Labels: documentation, ignore changelog

#13 Fix group markers don't check for tracker
  addons/friendly_tracker/XEH_PREP.hpp
  addons/friendly_tracker/functions/fnc_hasTracker.sqf
  addons/friendly_tracker/functions/fnc_isTrackable.sqf
  addons/friendly_tracker/functions/fnc_loop.sqf
Labels: bugfix

#14 Remove Eden categories
  addons/main/CfgEden.hpp
  addons/main/DisplayEden.hpp
  addons/main/config.cpp
Labels: cleanup
