Repository ArmaForces/FriendlyTracker, pull requests merged in 2020-02, with the labels that each got.

#17 Fix isTrackable check in loop
  addons/friendly_tracker/functions/fnc_loop.sqf
Labels: bugfix

#16 Bump version for release 1.0.3
  addons/main/script_version.hpp
Labels: ignore changelog

#18 Bump version for release 1.0.4
  addons/main/script_version.hpp
Labels: ignore changelog

#19 Fix loop syntax error
  addons/friendly_tracker/functions/fnc_loop.sqf
Labels: bugfix

#20 Add CODEOWNERS file
  .github/CODEOWNERS
Labels: enhancement, ignore changelog

#21 Add group name to vehicle marker if leader is in vehicle
  addons/friendly_tracker/functions/fnc_createGroupMarker.sqf
Labels: feature

#22 Bump version for release 1.0.5
  addons/main/script_version.hpp
Labels: ignore changelog

#24 Do not show enemy groups
  addons/friendly_tracker/functions/fnc_createVehicleMarker.sqf
  addons/friendly_tracker/functions/fnc_getGroupMarkerType.sqf
  addons/friendly_tracker/functions/fnc_loop.sqf
  addons/friendly_tracker/script_component.hpp
Labels: bugfix

#25 Add setting to enable showing of invisible units on tracker (default: disabled)
  addons/friendly_tracker/XEH_PREP.hpp
  addons/friendly_tracker/functions/fnc_canTrack.sqf
  addons/friendly_tracker/functions/fnc_isTrackable.sqf
  addons/friendly_tracker/functions/fnc_loop.sqf
  addons/friendly_tracker/initSettings.sqf
  addons/friendly_tracker/stringtable.xml
Labels: feature
